### ISSUE TITLE
THX FOR STARTING

### ISSUE THREAD

**Issue by matthew4444** [UniversalMine/UniversalMine-MP#1]
thx for starting, this proxy src @erkam2002  and @RedstoneAlmeida :)

**Comment by erkam2002** [comment]
I have invited a friend in UniversalMine :)

**Comment by matthew4444** [comment]
ok, who is it?

**Comment by erkam2002** [comment]
Henning-Klatt

**Comment by matthew4444** [comment]
ok :)
